services:
  auth_service:
    build:
      context: ./backend
      dockerfile: ./apps/auth/Dockerfile
      target: development
    command: pnpm run start:dev auth
    # command: tail -f /dev/null
    env_file:
      - ./backend/apps/auth/.env.docker
    volumes:
      - ./backend/apps/auth:/usr/src/app/auth
      - ./backend/libs:/usr/src/app/libs

  rooms_service:
    build:
      context: ./backend
      dockerfile: ./apps/rooms/Dockerfile
      target: development
    command: pnpm run start:dev rooms
    # command: tail -f /dev/null
    env_file:
      - ./backend/apps/rooms/.env.docker
    volumes:
      - ./backend/apps/rooms:/usr/src/app/rooms
      - ./backend/libs:/usr/src/app/libs

  notifications_service:
    build:
      context: ./backend
      dockerfile: ./apps/notifications/Dockerfile
      target: development
    command: pnpm run start:dev notifications
    # command: tail -f /dev/null
    env_file:
      - ./backend/apps/notifications/.env.docker
    volumes:
      - ./backend/apps/notifications:/usr/src/app/notifications
      - ./backend/libs:/usr/src/notifications/libs

  frontend_service:
    build:
      context: ./frontend/main
      dockerfile: ./Dockerfile
    env_file:
      - ./frontend/main/.env.docker
    volumes:
      - ./frontend/main:/usr/src/app

  nginx:
    image: nginx:latest
    container_name: nginx-api-gateway
    ports:
      - "8000:8000"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - auth_service
      - rooms_service
      - frontend_service

  postgres:
    image: postgres:15
    ports:
      - '5434:5432'
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/init-auth_service-db.sh:/docker-entrypoint-initdb.d/init-auth_service-db.sh
      - ./backend/init-rooms_service-db.sh:/docker-entrypoint-initdb.d/init-rooms_service-db.sh

  redis:
    restart: always
    image: redis:alpine
    ports:
      - 6380:6379

volumes:
  postgres_data:
